# Generated by Django 6.0.1 on 2026-01-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTreasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب/الخزنة')),
                ('type', models.CharField(choices=[('CASH', 'خزينة نقدية'), ('BANK', 'حساب بنكي')], max_length=10, verbose_name='النوع')),
                ('currency', models.CharField(choices=[('YER', 'رال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], max_length=3, verbose_name='العملة')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='الرصيد الحالي')),
            ],
            options={
                'verbose_name': 'خزينة/حساب بنكي',
                'verbose_name_plural': 'أصول الشركة (خزائن وبنوك)',
            },
        ),
        migrations.CreateModel(
            name='CompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.companytreasury', verbose_name='الخزينة/الحساب')),
            ],
            options={
                'verbose_name': 'حركة مالية للشركة',
                'verbose_name_plural': 'سجل حركات الشركة',
                'ordering': ['-created_at'],
            },
        ),
    ]
