# Generated by Django 6.0.1 on 2026-01-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('YER', 'ريال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], max_length=3)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'إيداع'), ('WITHDRAW', 'سحب'), ('TRANSFER', 'تحويل P2P'), ('EXCHANGE', 'صرافة')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
