# Generated by Django 6.0.1 on 2026-01-15 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='من عملة')),
                ('to_currency', models.CharField(max_length=3, verbose_name='إلى عملة')),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='المبلغ المرسل')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='سعر الصرف المستخدم')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='المبلغ المستلم')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عملية تحويل عملة',
                'verbose_name_plural': 'عمليات تحويل العملات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('YER', 'ريال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], max_length=3, verbose_name='من عملة')),
                ('to_currency', models.CharField(choices=[('YER', 'ريال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], max_length=3, verbose_name='إلى عملة')),
                ('buy_rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='سعر الشراء')),
                ('sell_rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='سعر البيع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'سعر صرف',
                'verbose_name_plural': 'أسعار الصرف',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
