# Generated by Django 6.0.1 on 2026-01-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_currencyconversion_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconversion',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم المرجعي'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم المرجعي'),
        ),
    ]
