# Generated by Django 6.0.1 on 2026-01-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_expiry_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_issue_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_issuer',
            new_name='issuer',
        ),
    ]
