# Generated by Django 6.0.1 on 2026-01-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_id_expiry_date_user_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_photo_back',
            new_name='id_back',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_photo_front',
            new_name='id_front',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_photo_selfie',
            new_name='selfie',
        ),
    ]
