# Generated by Django 6.0.1 on 2026-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف البديل'),
        ),
    ]
