# Generated by Django 6.0.1 on 2026-01-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'إشعار جماعي',
                'verbose_name_plural': 'الإشعارات الجماعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
